title: East End Collaboratory
description: >- # this means to ignore newlines until "baseurl:"
  The mission of the East End Collaboratory is to support the community effort to restore East End 
  Cemetery by engaging students and faculty across disciplines and institutions. Their work entails 
  the curation and documentation of African American history and culture in Richmond, as well as the 
  reclamation of the cemetery site. The Collaboratory aims to produce place-based knowledge that 
  contributes to a community dialogue about our collective past.
baseurl: "" 
url: ""

page_gen:
  - data: 'test_records'
    template: 'person'
    name: 'SSID'
    dir: 'people'
  # - data: 'full_records'
  #   template: 'person'
  #   name: 'SSID'
  #   dir: 'people'


# Build settings
theme: minima
plugins:
  - jekyll-feed
show_excerpts: true
header_pages:
  - home.md
  - about.md
  - links.md
  - news.html
  - faq.md
  - contact.html
  - suggest.html
  - search.html

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
