title: East End Cemetery Collaboratory
baseurl: ''
url: ''

page_gen:
  # - data: 'test_records'
  - data: 'full_records'
    template: 'person'
    name: 'SSID'
    dir: 'people'

# Build settings
theme: minima
plugins:
  - jekyll-feed
show_excerpts: true

collections:
  - links
  - pages

assets:
  sources:
    - assets/fonts
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
